INPUT "HOW OLD ARE YOU?", A
H = A / 2
REM "AGE OF TINY BASIC"
T = 2021 - 1975
IF A > T PRINT "YOU ARE OLDER THAN ME"
90 IF A<T PRINT "YOU ARE YOUNGER THAN ME"
RND R
110 PRINT "CATCH RANDOM VALUE", R, " BYE!"
