DIM A AS INTEGER
DIM B AS LONG
DIM S AS STRING
S = "HOW OLD ARE YOU?"
INPUT S, A
LET B = 234 - 5 * 6/2 + 32
REM "AGE OF TINY BASIC"
DIM T AS SINGLE
T = 2021 - 1975
IF A > T PRINT "YOU ARE OLDER THAN ME"
90 IF A<T PRINT "YOU ARE YOUNGER THAN ME"
RND R
110 PRINT "CATCH RANDOM VALUE ", R, " BYE!"
120 PRINT "B VALUE IS:", B, "HMM... WHAT ELSE?"
