DIM A AS INTEGER
DIM B AS LONG
DIM S AS STRING
LET S = "HOW OLD ARE YOU?"
INPUT S, A
LET B = 234 - 5 * 6/(2 + 32)+13
REM "AGE OF TINY BASIC"
DIM T AS SINGLE
LET T = 2021 - 1975
GOSUB 200
RND R
110 PRINT "CATCH RANDOM VALUE ", R, " BYE!"
120 PRINT "B VALUE IS:", B, "HMM... WHAT ELSE?"

200 PRINT "I AM PROCESSING..."
    IF A > T THEN PRINT "YOU ARE OLDER THAN ME"
210 IF A<T THEN PRINT "YOU ARE YOUNGER THAN ME"
    RETURN
    PRINT "AFTER SUBPROC"
