DIM A AS INTEGER
DIM B AS INTEGER
PRINT "WHATS YOUR NUMBER?"
PRINT "HOW OLD ARE YOU?"
INPUT B, A
REM "AGE OF TINY BASIC"
20 DIM T AS SINGLE
LET T = 2021 - 1975
GOSUB 200
190 PRINT "BEFORE SUBPROC"
200 PRINT "IN THE SUBPROC"
210 IF A > T THEN PRINT "YOU ARE OLDER THAN ME"
220 IF A<T THEN PRINT "YOU ARE YOUNGER THAN ME"
230 RETURN
240 PRINT "AFTER SUBPROC"
